### ISSUE TITLE
About Us: Clarification (Dot Pattern Color)

### ISSUE THREAD

**Issue by AzeemQaiser** [AzeemQaiser/kami-vision.github.io#3]
The dot pattern on the page have colours which are not defined in your colour guide. Can you please give those colours.

**Comment by AzeemQaiser** [comment]
Dot Color: #90B2CB
Opacity: 20%
Dot Size: 12X12
Gap between dots: 50 PX

**Comment by sugavaneshwaran35** [comment]
color pattern applied in about us screen.
