### ISSUE TITLE
Contact Us: Pattern and Form Alignment issues

### ISSUE THREAD

**Issue by AzeemQaiser** [AzeemQaiser/kami-vision.github.io#9]
![image](https://user-images.githubusercontent.com/7283796/95609981-95534300-0a2d-11eb-95db-10d4e41b4bf0.png)

**Comment by sugavaneshwaran35** [comment]
We are unable to simulate the above issue. We will check on different machines and update on this issue

**Comment by sugavaneshwaran35** [comment]
design changed
